---  
# file: application.yml

- hosts: application
  vars_files:
    - vars/default.yml

  tasks:
    - name: Application; Add Opera PPA key
      apt_key: url=http://deb.opera.com/archive.key state=present
    - name: Application; Add Opera PPA
      apt_repository: repo="deb http://deb.opera.com/opera/ stable non-free" state=present

    - name: Application; Add Chrome PPA key
      apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
    - name: Application; Add Google Chrome PPA
      apt_repository: repo="deb http://dl.google.com/linux/chrome/deb/ stable main" state=present
                                
    - name: Application; Add Nextcloud PPA
      apt_repository: repo="ppa:nextcloud-devs/client"
                                
    - name: Application; standard packages
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'opera-stable', 'google-chrome-stable', 'nextcloud-client', 'tomboy', 'keepassx', 'flameshot', 'git', 'cinnamon', 'prime-phylo' ]



