---
# file: common.yml
- hosts: all
  vars_files:
    - vars/default.yml

  tasks:

    - name: Common; standard packages
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'net-tools', 'vim']

    - name: Common; bash environment (console user, non gui)
      template:
        src: files/custom.sh
        dest: "/etc/profile.d/custom.sh"

    - name: Common; /etc/skel bash environment
      template:
        src: "files/{{ item }}"
        dest: /etc/skel/
      loop: [ '.bash_aliases' ,'.bashrc' ]