---  
# file: fixes.yml
- hosts: all
  vars_files:
    - vars/default.yml

  tasks:
      
    # https://github.com/TurboVNC/turbovnc/issues/47
    - name: Bug/workaround for Ubuntu 18 / Gnome 3 popup 'Authentication is required to create a color profile'
      copy:
        src=files/45-allow.colord.pkla
        dest=/etc/polkit-1/localauthority/50-local.d/
        
    # After Google chrome installation, the repo is listed two times
    - name: Remove doubled google chrome repo
      file:
        path=/etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list
        state=absent
        
    # No BTRFS at all
    - name: Remove BTRFS
      apt:
        name=btrfs-progs
        state=absent
        
      tags: fixes
        

