---  
# file: site.yml

# General Setup
- import_playbook: common.yml

# Install to trigger possible dependencies
- import_playbook: virtualgl.yml

# nVidia should be installed after first VirtualGL installation.
- import_playbook: nvidia.yml

# Repeat this step to configure VirtualGL
- import_playbook: virtualgl.yml

# Thinlinc Installation / Configuration
- import_playbook: thinlinc.yml

# Various fixes
- import_playbook: fixes.yml

# KVM
- import_playbook: kvm.yml

# General Application
- import_playbook: application.yml

# Auto Update
- import_playbook: autoupdate.yml

- hosts: all
  vars_files:
    - vars/default.yml

  tasks:

