---  

# file: site.yml
- import_playbook: common.yml

# Install to trigger possible dependencies
- import_playbook: virtualgl.yml

# nVidia should be installed after first VirtualGL installation.
- import_playbook: nvidia.yml

# Repeat this step to configure VirtualGL
- import_playbook: virtualgl.yml

# Thinlinc Installation / Configuration
- import_playbook: thinlinc.yml

# Various fixes
- import_playbook: fixes.yml

# KVM
- import_playbook: kvm.yml

- hosts: all
  vars_files:
    - vars/default.yml

  tasks:
    # General Information to 'sysadmin', collected through the run
    - debug: msg="site; {{ thinlinc_set_pw }}"

