---
# file: thinlinc.yml
- hosts: thinlinc
  vars_files:
    - vars/default.yml
  vars:
    - tl_version: 4.11.0
    - tl_server_pkg: /zfs/data/iso/thinlinc/tl-{{ tl_version }}-server.zip
    - tl_client_pkg: /zfs/data/iso/thinlinc/thinlinc-client_{{ tl_version }}-6323_amd64.deb

  user: "{{ ansible_user }}"
  tasks:

  - name: Prerequisites for ThinLinc
    apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
    loop: [ 'python', 'python-gtk2', 'python-apt', 'python-pyasn1',  'python-ldap' ]

  - name: Copy ThinLinc Server Installer
    synchronize: 
      archive: yes 
      delete: yes 
      dest: /tmp/tlserver 
      src: "{{ tl_server_pkg }}"
 
  - name: Install ThinLinc Packages
      apt: deb=/tmp/tlserver/packages/{{ item }} force=yes state=present
      with_items:
        # - thinlinc-rdesktop_{{ tl_version }}-{{ tl_build }}_amd64.deb
        - thinlinc-tladm_{{ tl_version }}-{{ tl_build }}_amd64.deb
        - thinlinc-tlmisc-libs32_{{ tl_version }}-{{ tl_build }}_amd64.deb
        - thinlinc-tlmisc-libs_{{ tl_version }}-{{ tl_build }}_amd64.deb
        - thinlinc-tlmisc_{{ tl_version }}-{{ tl_build }}_amd64.deb
        - thinlinc-tlprinter_{{ tl_version }}-{{ tl_build }}_all.deb
        - thinlinc-vnc-server_{{ tl_version }}-{{ tl_build }}_amd64.deb
        - thinlinc-vsm_{{ tl_version }}-{{ tl_build }}_amd64.deb
        - thinlinc-webaccess_{{ tl_version }}-{{ tl_build }}_all.deb
 
