---
# file: thinlinc.yml
- hosts: thinlinc
  vars_files:
    - vars/default.yml
  vars:
    - tl_version: 4.11.0
    - tl_build: 6323
    - tl_server_pkg: /zfs/data/iso/thinlinc/tl-{{ tl_version }}-server.zip
    - tl_client_pkg: /zfs/data/iso/thinlinc/thinlinc-client_{{ tl_version }}-6323_amd64.deb
    - tl_answer: tl_setup_answer-{{ tl_version }}.txt

  user: "{{ ansible_user }}"
  tasks:

  - name: ThinLinc; Prerequisites
    apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
    loop: [ 'python', 'python-gtk2', 'python-apt', 'python-pyasn1',  'python-ldap' ]

  - name: ThinLinc; Copy Server Installer
    synchronize: 
      archive: yes 
      delete: yes 
      dest: /tmp/tlserver.zip 
      src: "{{ tl_server_pkg }}"
 
  - name: ThinLinc; Install Packages
    apt: deb=/tmp/tl-{{ tl_version }}-server/packages/{{ item }} force=yes state=present
    with_items:
      # - thinlinc-rdesktop_{{ tl_version }}-{{ tl_build }}_amd64.deb
      - thinlinc-tladm_{{ tl_version }}-{{ tl_build }}_amd64.deb
      - thinlinc-tlmisc-libs32_{{ tl_version }}-{{ tl_build }}_amd64.deb
      - thinlinc-tlmisc-libs_{{ tl_version }}-{{ tl_build }}_amd64.deb
      - thinlinc-tlmisc_{{ tl_version }}-{{ tl_build }}_amd64.deb
      - thinlinc-tlprinter_{{ tl_version }}-{{ tl_build }}_all.deb
      - thinlinc-vnc-server_{{ tl_version }}-{{ tl_build }}_amd64.deb
      - thinlinc-vsm_{{ tl_version }}-{{ tl_build }}_amd64.deb
      - thinlinc-webaccess_{{ tl_version }}-{{ tl_build }}_all.deb
 
  - name: ThinLinc; Copy answer file
    template: src=files/{{ tl_answer }} dest=/tmp/

  - name: ThinLinc; Configure ThinLinc
    shell: /opt/thinlinc/sbin/tl-setup -a /tmp/{{ tl_answer }}

  - name: ThinLinc; Remove answer file
    file: path=/tmp/{{ tl_answer }} state=absent

