---
# file: common.yml
- hosts: virtualgl
  vars_files:
    - vars/default.yml

  user: "{{ ansible_user }}"
  tasks:
    - name: Copy virtualgl.deb
      copy: 
        dest: /tmp/vgl.deb
        src: /zfs/data/iso/virtualgl/virtualgl_2.6.3_amd64.deb

    - name: Install VirtualGL
      apt: deb=/tmp/vgl.deb force=yes state=present

    - name: Configure VirtualGL  
      shell: /opt/VirtualGL/bin/vglserver_config -config +s +f +t

